version: '3.3'
services:
  bot:
    build: .
    restart: always
    environment:
      API_URL: ${API_URL:-http://shambuwu.com}
      API_PORT: ${API_PORT:-8080}
      APP_PORT: ${APP_PORT:-80}
      APP_PORT_DEV: ${APP_PORT_DEV:-80}
    volumes:
      - ./:/var/app/:cached
    command: 'npm start'